# Generated by Django 2.2.3 on 2019-07-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('Author', models.CharField(max_length=250)),
                ('Edition', models.CharField(max_length=10)),
                ('thumbnail', models.ImageField(upload_to='images')),
                ('kindle', models.FileField(upload_to='files')),
                ('slug', models.SlugField(unique=True)),
                ('published', models.DateTimeField()),
            ],
        ),
    ]
